#!/bin/sh
# OpenIPC-on-TF shim: 本 TF rootfs 无 ipcinfo(OpenIPC 的 IPCam 信息工具)。
# S70vendor 用 `ipcinfo -v` 选 load_<soc> 脚本; load_hisilicon 仅在未显式给 SENSOR 时才用 --short-sensor。
case "$1" in
	--chip-name)    echo hi3516cv610 ;;
	--short-sensor) echo os05l10 ;;
	-v)             echo 3516cv610_20s ;;
	*)              echo hi3516cv610 ;;
esac
exit 0
